on:
  - push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt update
          sudo apt install build-essential libfuse2 -y
          sudo apt install qtbase5-dev qt5-qmake libmpv-dev zlib1g-dev -y
      - run: |
          wget https://github.com/moomiji/KikoPlay/releases/download/0.9.0/1.zip
          unzip 1.zip
          cd KikoPlay
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage
          sed -i 's!/usr/share/pixmaps/!!g' kikoplay.desktop
          cat kikoplay.desktop

      - run: |
          cd KikoPlay
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt -e AppDir/usr/bin/KikoPlay -d kikoplay.desktop -i res/images/kikoplay-4.png
          rm linuxdeploy*.AppImage
          ls -al 

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: 2
          path: /home/runner/work/KikoPlay/
