on:
  - push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '5c9234bce550cc29ca82552244dc109018388264'
      - run: |
          sudo apt update
          sudo apt install build-essential libfuse2 -y
          sudo apt install qtbase5-dev qt5-qmake libmpv-dev zlib1g-dev -y
      - run: qmake build.pro
      - run: make install INSTALL_ROOT=AppDir
      - run: make -j $(nproc)

      - name: Upload 
        uses: actions/upload-artifact@main
        with:
          name: 1
          path: /home/runner/work/KikoPlay/
